/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paurush.mne;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MnEApplication {
	public static void main(String[] args) {
		SpringApplication.run(MnEApplication.class, args);
	}
}
